export { default as Table } from "./Table.vue";
export { default as TableBody } from "@/components/external/shadcn/table/TableBody.vue";
export { default as TableCaption } from "@/components/external/shadcn/table/TableCaption.vue";
export { default as TableCell } from "@/components/external/shadcn/table/TableCell.vue";
export { default as TableEmpty } from "@/components/external/shadcn/table/TableEmpty.vue";
export { default as TableFooter } from "@/components/external/shadcn/table/TableFooter.vue";
export { default as TableHead } from "@/components/external/shadcn/table/TableHead.vue";
export { default as TableHeader } from "@/components/external/shadcn/table/TableHeader.vue";
export { default as TableRow } from "@/components/external/shadcn/table/TableRow.vue";
